@App.API_HostAddress = https://localhost:7172
@contentType = application/json

### Log in as admin to get a token
# @name login
POST {{App.API_HostAddress}}/api/v1/auth/login
Content-Type: {{contentType}}

{
  "email": "admin@campanion.com",
  "password": "Admin@123!"
}

###
# @name allUsersAdmin
GET {{App.API_HostAddress}}/api/v1/users/allusers
Authorization: Bearer {{login.response.body.$.token}}

###
# @name allUsersNonAdmin
GET {{App.API_HostAddress}}/api/v1/users/allusers

### Use the captured token on a protected endpoint
GET {{App.API_HostAddress}}/api/v1/campgrounds
Authorization: Bearer {{login.response.body.$.token}}

### Register as a new user
# @name register
POST {{App.API_HostAddress}}/api/v1/auth/register
Content-Type: {{contentType}}

{
  "appUserPassword": "aBc123!",
  "appUserUsername": "AppUser01",
  "appUserEmail": "email@email.ca",
  "appUserPhone": "9995551234",
  "appUserFirstName": "App",
  "appUserLastName": "User01",
  "appUserStreetAddress": "123 Main St",
  "appUserCity": "Toronto",
  "appUserProvince": "Ontario",
  "appUserCountry": "Canada",
  "appUserPostalCode": "N1G1E1"
}

### View profile upon registration
# @name profile
GET {{App.API_HostAddress}}/api/v1/profiles/profile
Authorization: Bearer {{register.response.body.$.token}}